In [1]:
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfTransformer

/home/aryansharma/Desktop/Aryan Pendrive Data/Support-Integrity-Auditor/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
print("="*50)
print("Loading Sentence Transformer...")
print("="*50)
encoder = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

==================================================
Loading Sentence Transformer...
==================================================

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7774.64it/s]

In [146]:
def encoding(row):
    return encoder.encode(f"{row['Ticket_Subject']} | {row['Ticket_Description']}")

In [147]:
import pandas as pd

In [148]:
df = pd.read_csv("../dataset/preprocessed_data.csv")

In [149]:
results = []
for idx,row in df.iterrows():
    if(idx+1)%1000==0:
        print(f"{idx+1} Completed")
    results.append(encoding(row))

1000 Completed
2000 Completed
3000 Completed
4000 Completed
5000 Completed
6000 Completed
7000 Completed
8000 Completed
9000 Completed
10000 Completed
11000 Completed
12000 Completed
13000 Completed
14000 Completed
15000 Completed
16000 Completed
17000 Completed
18000 Completed
19000 Completed
20000 Completed

In [150]:
encod_df = pd.DataFrame(results,index=df.Ticket_ID)
encod_df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
Ticket_ID,,,,,,,,,,,,,,,,,,,,,
TKT-100000,0.020240,-0.006071,0.052954,0.038421,-0.024569,-0.036776,0.021148,-0.023323,-0.035957,-0.022554,...,-0.017878,0.065636,0.056690,-0.015246,0.036319,0.054365,-0.033924,0.003157,-0.065000,-0.005305
TKT-100001,0.016025,-0.057607,0.017116,-0.000881,-0.076159,0.013830,-0.072179,-0.035292,-0.064066,-0.045000,...,0.043005,-0.000897,0.009951,0.016805,0.048493,-0.034435,0.041469,0.014642,-0.048687,-0.007805
TKT-100002,0.011760,-0.004075,0.069617,-0.025910,0.020714,0.041296,-0.002445,0.015871,-0.113202,-0.020245,...,-0.076056,-0.048143,-0.017498,0.055358,-0.058224,0.055917,0.035862,-0.018399,-0.006205,0.046446
TKT-100003,0.002673,0.015258,-0.002575,-0.084914,0.039865,-0.051279,-0.005452,0.006824,-0.013828,-0.013040,...,-0.013255,-0.005663,-0.010502,0.066965,-0.054884,-0.021497,0.036692,0.022927,0.015537,-0.020427
TKT-100004,-0.046125,-0.001081,0.048228,0.011123,-0.038715,-0.024981,-0.017508,-0.002243,-0.066401,0.061479,...,0.006765,-0.022577,0.026608,-0.015839,-0.051740,-0.021331,0.125839,-0.027864,0.001826,0.028594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TKT-119995,0.069429,-0.055084,0.040869,-0.052215,-0.029319,-0.027651,-0.011467,0.042361,-0.092540,0.034184,...,0.023547,0.004857,0.031628,0.009623,0.086230,-0.059772,0.135354,-0.003723,-0.006510,0.026256
TKT-119996,-0.071529,-0.009974,0.012739,0.005684,0.078907,-0.058134,0.130325,-0.020655,0.058792,0.018808,...,-0.032569,-0.034864,0.028600,-0.021845,0.015639,0.034212,0.101279,-0.069050,0.006489,0.068474
TKT-119997,-0.068554,-0.019892,0.081615,-0.011759,0.130141,-0.021089,-0.021305,-0.062330,-0.062667,0.018018,...,-0.068565,-0.062206,0.120479,-0.012882,0.044700,0.024568,0.041998,-0.079686,-0.041692,-0.000061
TKT-119998,-0.039257,0.088679,-0.012890,-0.014775,0.026264,-0.062684,0.001521,-0.058871,-0.014164,0.049993,...,0.008215,-0.028863,0.023736,0.021763,-0.010205,0.041824,0.148133,-0.087361,0.033356,0.021304
TKT-119999,-0.085666,-0.035889,0.027839,-0.056243,0.017435,-0.015594,-0.132421,-0.023175,-0.176227,0.003478,...,0.084057,0.129782,0.020823,-0.015930,-0.010086,-0.015617,0.117823,-0.010765,-0.061708,0.096499

In [151]:
df = df.set_index("Ticket_ID")

In [152]:
df

,Customer_Name,Customer_Email,Ticket_Subject,Ticket_Description,Issue_Category,Priority_Level,Ticket_Channel,Submission_Date,Resolution_Time_Hours,Assigned_Agent,Satisfaction_Score,low_score,medium_score,high_score,critical_score,Final_severity_label,Is_Mismatch
Ticket_ID,,,,,,,,,,,,,,,,,
TKT-100000,George Simon,lisastrickland@example.com,Hours of operation - Individual,"Hi Support, Where is your headquarters located...",General Inquiry,High,Web Form,2025-07-02,43,David Kim,5,0.378039,0.140941,0.172135,0.153768,LOW,1
TKT-100001,Scott Thompson,wevans@example.org,Data not syncing - Card,"Hi Support, The application crashes every time...",Technical,High,Chat,2025-06-28,41,Elena Rodriguez,5,0.266401,0.381068,0.246063,0.151325,MEDIUM,1
TKT-100002,Jennifer Smith,oleonard@example.net,2FA issues - Question,"Hi Support, How do I upgrade to the Enterprise...",Account,High,Web Form,2025-02-05,7,Anya Sharma,5,0.332876,0.122415,0.334390,0.167953,HIGH,0
TKT-100003,Rachel Bullock,katherine67@example.net,Login failed - Let,"Hi Support, The dashboard is not loading any d...",Technical,Low,Web Form,2025-03-20,41,Anya Sharma,5,0.222336,0.458418,0.368047,0.268405,MEDIUM,1
TKT-100004,Thomas Parks DDS,raykelsey@example.com,Refund status - Attention,"Hi Support, I have been trying to update my pa...",Billing,Medium,Email,2025-04-27,40,David Kim,5,0.330313,0.241895,0.470279,0.134315,HIGH,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TKT-119995,Jason Stewart,Susan.Valenzuela@enterprise.org,Installation issue - Think,"Hi Support, The application crashes every time...",Technical,High,Web Form,2025-02-05,6,Anya Sharma,4,0.173028,0.404707,0.272886,0.225397,MEDIUM,1
TKT-119996,Amy Moore,meganfranklin@example.net,Alert notification - Reality,"Hi Support, I received a suspicious email clai...",Fraud,Critical,Chat,2024-08-07,10,Elena Rodriguez,3,0.217183,0.128328,0.316290,0.386094,CRITICAL,0
TKT-119997,Ann Smith,Matthew.Landry@tech.io,Subscription upgrade - Spring,"Hi Support, My profile picture is not updating...",Account,Medium,Web Form,2025-10-07,2,David Kim,4,0.409587,0.206950,0.244298,0.151840,LOW,1
TKT-119998,Dennis Moore,traceyreed@example.com,Suspicious charge - Even,"Hi Support, I have been trying to update my pa...",Billing,High,Web Form,2024-01-31,8,Anya Sharma,1,0.256588,0.191294,0.487348,0.177058,HIGH,0
TKT-119999,Monica Powell,blairchristine@example.net,Demo request - Six,"Hi Support, Is there a roadmap for new feature...",General Inquiry,Low,Web Form,2025-09-14,20,Elena Rodriguez,4,0.482580,0.126670,0.135661,0.095552,LOW,0

In [153]:
df["Final_severity_label"] = df["Final_severity_label"].map({"LOW":0,"MEDIUM":1,"HIGH":2,"CRITICAL":3})
df["Priority_Level"] = df["Priority_Level"].map({"Low":0,"Medium":1,"High":2,"Critical":3})

In [154]:
encod_df["Target"] = df["Final_severity_label"]
priority = df["Priority_Level"]

In [155]:
encod_df

,0,1,2,3,4,5,6,7,8,9,...,375,376,377,378,379,380,381,382,383,Target
Ticket_ID,,,,,,,,,,,,,,,,,,,,,
TKT-100000,0.020240,-0.006071,0.052954,0.038421,-0.024569,-0.036776,0.021148,-0.023323,-0.035957,-0.022554,...,0.065636,0.056690,-0.015246,0.036319,0.054365,-0.033924,0.003157,-0.065000,-0.005305,0
TKT-100001,0.016025,-0.057607,0.017116,-0.000881,-0.076159,0.013830,-0.072179,-0.035292,-0.064066,-0.045000,...,-0.000897,0.009951,0.016805,0.048493,-0.034435,0.041469,0.014642,-0.048687,-0.007805,1
TKT-100002,0.011760,-0.004075,0.069617,-0.025910,0.020714,0.041296,-0.002445,0.015871,-0.113202,-0.020245,...,-0.048143,-0.017498,0.055358,-0.058224,0.055917,0.035862,-0.018399,-0.006205,0.046446,2
TKT-100003,0.002673,0.015258,-0.002575,-0.084914,0.039865,-0.051279,-0.005452,0.006824,-0.013828,-0.013040,...,-0.005663,-0.010502,0.066965,-0.054884,-0.021497,0.036692,0.022927,0.015537,-0.020427,1
TKT-100004,-0.046125,-0.001081,0.048228,0.011123,-0.038715,-0.024981,-0.017508,-0.002243,-0.066401,0.061479,...,-0.022577,0.026608,-0.015839,-0.051740,-0.021331,0.125839,-0.027864,0.001826,0.028594,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TKT-119995,0.069429,-0.055084,0.040869,-0.052215,-0.029319,-0.027651,-0.011467,0.042361,-0.092540,0.034184,...,0.004857,0.031628,0.009623,0.086230,-0.059772,0.135354,-0.003723,-0.006510,0.026256,1
TKT-119996,-0.071529,-0.009974,0.012739,0.005684,0.078907,-0.058134,0.130325,-0.020655,0.058792,0.018808,...,-0.034864,0.028600,-0.021845,0.015639,0.034212,0.101279,-0.069050,0.006489,0.068474,3
TKT-119997,-0.068554,-0.019892,0.081615,-0.011759,0.130141,-0.021089,-0.021305,-0.062330,-0.062667,0.018018,...,-0.062206,0.120479,-0.012882,0.044700,0.024568,0.041998,-0.079686,-0.041692,-0.000061,0
TKT-119998,-0.039257,0.088679,-0.012890,-0.014775,0.026264,-0.062684,0.001521,-0.058871,-0.014164,0.049993,...,-0.028863,0.023736,0.021763,-0.010205,0.041824,0.148133,-0.087361,0.033356,0.021304,2
TKT-119999,-0.085666,-0.035889,0.027839,-0.056243,0.017435,-0.015594,-0.132421,-0.023175,-0.176227,0.003478,...,0.129782,0.020823,-0.015930,-0.010086,-0.015617,0.117823,-0.010765,-0.061708,0.096499,0

In [156]:
from sklearn.model_selection import train_test_split

In [157]:
X_Train,X_test,y_train,y_test = train_test_split(encod_df.drop(columns=["Target"]), encod_df["Target"], test_size=0.2 ,stratify=encod_df["Target"])

In [158]:
priority_test = priority.loc[y_test.index]

In [159]:
priority_train = priority.loc[y_train.index]

In [160]:
mismatch_test = df["Is_Mismatch"].loc[y_test.index]
mismatch_train = df["Is_Mismatch"].loc[y_train.index]

In [161]:
X_Train.shape

(16000, 384)

In [162]:
from sklearn.ensemble import RandomForestClassifier

In [163]:
model = RandomForestClassifier()
model.fit(X_Train,y_train)

RandomForestClassifier()

In [164]:
from sklearn.metrics import classification_report

In [165]:
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.95      0.93      0.94      1558
           1       0.94      0.94      0.94       757
           2       0.91      0.93      0.92      1388
           3       0.89      0.89      0.89       297

    accuracy                           0.93      4000
   macro avg       0.92      0.92      0.92      4000
weighted avg       0.93      0.93      0.93      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.94      0.92      0.93      1346
           1       0.96      0.97      0.97      2654

    accuracy                           0.95      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.95      0.95      0.95      4000

In [166]:
from xgboost import XGBClassifier

In [167]:
model = XGBClassifier()
model.fit(X_Train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [168]:
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.95      0.94      0.94      1558
           1       0.94      0.94      0.94       757
           2       0.92      0.93      0.92      1388
           3       0.90      0.94      0.92       297

    accuracy                           0.93      4000
   macro avg       0.93      0.94      0.93      4000
weighted avg       0.93      0.93      0.93      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1346
           1       0.97      0.97      0.97      2654

    accuracy                           0.96      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.96      0.96      0.96      4000

In [169]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [170]:
model.fit(X_Train,y_train)

LogisticRegression()

In [171]:
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.95      0.93      0.94      1558
           1       0.94      0.95      0.94       757
           2       0.92      0.93      0.92      1388
           3       0.88      0.91      0.90       297

    accuracy                           0.93      4000
   macro avg       0.92      0.93      0.93      4000
weighted avg       0.93      0.93      0.93      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.95      0.93      0.94      1346
           1       0.96      0.97      0.97      2654

    accuracy                           0.96      4000
   macro avg       0.96      0.95      0.95      4000
weighted avg       0.96      0.96      0.96      4000

In [172]:
from sklearn.ensemble import GradientBoostingClassifier,HistGradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [173]:
model = DecisionTreeClassifier()
model = model.fit(X_Train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      1558
           1       0.87      0.86      0.86       757
           2       0.85      0.85      0.85      1388
           3       0.76      0.77      0.77       297

    accuracy                           0.86      4000
   macro avg       0.84      0.84      0.84      4000
weighted avg       0.86      0.86      0.86      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.89      0.86      0.87      1346
           1       0.93      0.95      0.94      2654

    accuracy                           0.92      4000
   macro avg       0.91      0.90      0.91      4000
weighted avg       0.92      0.92      0.92      4000

In [174]:
model = HistGradientBoostingClassifier()
model = model.fit(X_Train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1558
           1       0.94      0.94      0.94       757
           2       0.92      0.93      0.93      1388
           3       0.89      0.91      0.90       297

    accuracy                           0.93      4000
   macro avg       0.92      0.93      0.93      4000
weighted avg       0.93      0.93      0.93      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.94      0.93      0.94      1346
           1       0.97      0.97      0.97      2654

    accuracy                           0.96      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.96      0.96      0.96      4000

In [175]:
from lightgbm import LGBMClassifier

In [176]:
model = LGBMClassifier()
model = model.fit(X_Train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.023974 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 97920
[LightGBM] [Info] Number of data points in the train set: 16000, number of used features: 384
[LightGBM] [Info] Start training from score -0.943052
[LightGBM] [Info] Start training from score -1.663696
[LightGBM] [Info] Start training from score -1.058430
[LightGBM] [Info] Start training from score -2.602002
Classfication report

              precision    recall  f1-score   support

           0       0.95      0.94      0.94      1558
           1       0.94      0.94      0.94       757
           2       0.92      0.92      0.92      1388
           3       0.89      0.93      0.91       297

    accuracy                           0.93      4000
   macro avg       0.92      0.93      0.93      4000
weighted avg       0.93      0.93      0.93      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.94      0.93      0.94      1346
           1       0.97      0.97      0.97      2654

    accuracy                           0.96      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.96      0.96      0.96      4000

In [177]:
df

,Customer_Name,Customer_Email,Ticket_Subject,Ticket_Description,Issue_Category,Priority_Level,Ticket_Channel,Submission_Date,Resolution_Time_Hours,Assigned_Agent,Satisfaction_Score,low_score,medium_score,high_score,critical_score,Final_severity_label,Is_Mismatch
Ticket_ID,,,,,,,,,,,,,,,,,
TKT-100000,George Simon,lisastrickland@example.com,Hours of operation - Individual,"Hi Support, Where is your headquarters located...",General Inquiry,2,Web Form,2025-07-02,43,David Kim,5,0.378039,0.140941,0.172135,0.153768,0,1
TKT-100001,Scott Thompson,wevans@example.org,Data not syncing - Card,"Hi Support, The application crashes every time...",Technical,2,Chat,2025-06-28,41,Elena Rodriguez,5,0.266401,0.381068,0.246063,0.151325,1,1
TKT-100002,Jennifer Smith,oleonard@example.net,2FA issues - Question,"Hi Support, How do I upgrade to the Enterprise...",Account,2,Web Form,2025-02-05,7,Anya Sharma,5,0.332876,0.122415,0.334390,0.167953,2,0
TKT-100003,Rachel Bullock,katherine67@example.net,Login failed - Let,"Hi Support, The dashboard is not loading any d...",Technical,0,Web Form,2025-03-20,41,Anya Sharma,5,0.222336,0.458418,0.368047,0.268405,1,1
TKT-100004,Thomas Parks DDS,raykelsey@example.com,Refund status - Attention,"Hi Support, I have been trying to update my pa...",Billing,1,Email,2025-04-27,40,David Kim,5,0.330313,0.241895,0.470279,0.134315,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TKT-119995,Jason Stewart,Susan.Valenzuela@enterprise.org,Installation issue - Think,"Hi Support, The application crashes every time...",Technical,2,Web Form,2025-02-05,6,Anya Sharma,4,0.173028,0.404707,0.272886,0.225397,1,1
TKT-119996,Amy Moore,meganfranklin@example.net,Alert notification - Reality,"Hi Support, I received a suspicious email clai...",Fraud,3,Chat,2024-08-07,10,Elena Rodriguez,3,0.217183,0.128328,0.316290,0.386094,3,0
TKT-119997,Ann Smith,Matthew.Landry@tech.io,Subscription upgrade - Spring,"Hi Support, My profile picture is not updating...",Account,1,Web Form,2025-10-07,2,David Kim,4,0.409587,0.206950,0.244298,0.151840,0,1
TKT-119998,Dennis Moore,traceyreed@example.com,Suspicious charge - Even,"Hi Support, I have been trying to update my pa...",Billing,2,Web Form,2024-01-31,8,Anya Sharma,1,0.256588,0.191294,0.487348,0.177058,2,0
TKT-119999,Monica Powell,blairchristine@example.net,Demo request - Six,"Hi Support, Is there a roadmap for new feature...",General Inquiry,0,Web Form,2025-09-14,20,Elena Rodriguez,4,0.482580,0.126670,0.135661,0.095552,0,0

In [178]:
new_df = df[["Final_severity_label","Resolution_Time_Hours","Ticket_Channel", "Issue_Category","Satisfaction_Score"]]

In [179]:
new_df = pd.get_dummies(new_df,columns=["Ticket_Channel", "Issue_Category"], drop_first=True, dtype=int)

In [180]:
X_train,X_test,y_train,y_test = train_test_split(new_df.drop(columns=["Final_severity_label"]),new_df["Final_severity_label"], test_size=0.2, stratify=new_df["Final_severity_label"])

priority_train = df["Priority_Level"].loc[y_train.index]
priority_test = df["Priority_Level"].loc[y_test.index]

In [181]:
mismatch_test = df["Is_Mismatch"].loc[y_test.index]
mismatch_train = df["Is_Mismatch"].loc[y_train.index]

In [182]:
model = LogisticRegression()
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.87      0.88      0.88      1558
           1       0.64      1.00      0.78       757
           2       0.93      0.69      0.79      1388
           3       0.71      0.51      0.59       297

    accuracy                           0.81      4000
   macro avg       0.79      0.77      0.76      4000
weighted avg       0.83      0.81      0.81      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.80      0.88      0.84      1393
           1       0.93      0.88      0.91      2607

    accuracy                           0.88      4000
   macro avg       0.87      0.88      0.87      4000
weighted avg       0.89      0.88      0.88      4000

/home/aryansharma/Desktop/Aryan Pendrive Data/Support-Integrity-Auditor/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [183]:
model = XGBClassifier()
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.86      0.87      0.87      1558
           1       0.64      0.96      0.77       757
           2       0.89      0.69      0.78      1388
           3       0.69      0.47      0.56       297

    accuracy                           0.80      4000
   macro avg       0.77      0.75      0.74      4000
weighted avg       0.82      0.80      0.79      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.79      0.86      0.83      1393
           1       0.92      0.88      0.90      2607

    accuracy                           0.87      4000
   macro avg       0.86      0.87      0.86      4000
weighted avg       0.88      0.87      0.87      4000

In [184]:
encod_df[["Resolution_Time_Hours","Ticket_Channel", "Issue_Category","Satisfaction_Score"]] = df[["Resolution_Time_Hours","Ticket_Channel", "Issue_Category","Satisfaction_Score"]]

In [185]:
encod_df = pd.get_dummies(encod_df,columns=["Ticket_Channel", "Issue_Category"], drop_first=True, dtype=int)

In [186]:
X_train,X_test,y_train,y_test = train_test_split(encod_df.drop(columns=["Target"]),encod_df["Target"], test_size=0.2, stratify=encod_df["Target"])

In [187]:
from sklearn.preprocessing import StandardScaler

In [188]:
scaler = StandardScaler() 
X_train[['Resolution_Time_Hours','Satisfaction_Score']] = scaler.fit_transform(X_train[['Resolution_Time_Hours','Satisfaction_Score']])
X_test[['Resolution_Time_Hours','Satisfaction_Score']] = scaler.transform(X_test[['Resolution_Time_Hours','Satisfaction_Score']])

In [189]:
mismatch_test = df["Is_Mismatch"].loc[y_test.index]
mismatch_train = df["Is_Mismatch"].loc[y_train.index]
priority_train = df["Priority_Level"].loc[y_train.index]
priority_test = df["Priority_Level"].loc[y_test.index]

In [190]:
X_train.columns

Index([                               0,                                1,
                                      2,                                3,
                                      4,                                5,
                                      6,                                7,
                                      8,                                9,
       ...
                                    382,                              383,
                'Resolution_Time_Hours',             'Satisfaction_Score',
                 'Ticket_Channel_Email',        'Ticket_Channel_Web Form',
               'Issue_Category_Billing',           'Issue_Category_Fraud',
       'Issue_Category_General Inquiry',       'Issue_Category_Technical'],
      dtype='object', length=392)

In [191]:
emb_model = XGBClassifier()
meta_model = XGBClassifier()

emb_model.fit(X_train.drop(columns=['Resolution_Time_Hours','Satisfaction_Score','Ticket_Channel_Email','Ticket_Channel_Web Form','Issue_Category_Billing','Issue_Category_Fraud','Issue_Category_General Inquiry','Issue_Category_Technical']),y_train)
meta_model.fit(X_train[['Resolution_Time_Hours','Satisfaction_Score','Ticket_Channel_Email','Ticket_Channel_Web Form','Issue_Category_Billing','Issue_Category_Fraud','Issue_Category_General Inquiry','Issue_Category_Technical']],y_train)

emb_prob = emb_model.predict_proba(X_test.drop(columns=['Resolution_Time_Hours','Satisfaction_Score','Ticket_Channel_Email','Ticket_Channel_Web Form','Issue_Category_Billing','Issue_Category_Fraud','Issue_Category_General Inquiry','Issue_Category_Technical']))
meta_prob = meta_model.predict_proba(X_test[['Resolution_Time_Hours','Satisfaction_Score','Ticket_Channel_Email','Ticket_Channel_Web Form','Issue_Category_Billing','Issue_Category_Fraud','Issue_Category_General Inquiry','Issue_Category_Technical']])

In [192]:
final_prob = 0.6*emb_prob + 0.4*meta_prob

In [193]:
final_prob

array([[7.8239761e-02, 8.0076516e-01, 7.9838708e-02, 4.1156396e-02],
       [2.9048171e-02, 2.0966963e-04, 6.7650247e-01, 2.9423970e-01],
       [1.0133090e-02, 8.8899660e-01, 5.0844859e-02, 5.0025549e-02],
       ...,
       [9.9993777e-01, 4.0078880e-06, 5.1546005e-05, 6.6536618e-06],
       [8.0455141e-03, 2.0262667e-05, 9.9191654e-01, 1.7779001e-05],
       [4.8529851e-01, 2.3512875e-05, 5.1466411e-01, 1.3874893e-05]],
      shape=(4000, 4), dtype=float32)

In [194]:
import numpy as np

In [195]:
y_pred = []
for prob in final_prob:
    y_pred.append(np.argmax(prob))

In [196]:
report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.95      0.93      0.94      1558
           1       0.94      0.97      0.95       757
           2       0.92      0.93      0.92      1388
           3       0.90      0.91      0.90       297

    accuracy                           0.93      4000
   macro avg       0.93      0.93      0.93      4000
weighted avg       0.93      0.93      0.93      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1394
           1       0.97      0.97      0.97      2606

    accuracy                           0.96      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.96      0.96      0.96      4000

In [197]:
emb_model = LGBMClassifier()
meta_model = LGBMClassifier()

emb_model.fit(X_train.drop(columns=['Resolution_Time_Hours','Satisfaction_Score','Ticket_Channel_Email','Ticket_Channel_Web Form','Issue_Category_Billing','Issue_Category_Fraud','Issue_Category_General Inquiry','Issue_Category_Technical']),y_train)
meta_model.fit(X_train[['Resolution_Time_Hours','Satisfaction_Score','Ticket_Channel_Email','Ticket_Channel_Web Form','Issue_Category_Billing','Issue_Category_Fraud','Issue_Category_General Inquiry','Issue_Category_Technical']],y_train)

emb_prob = emb_model.predict_proba(X_test.drop(columns=['Resolution_Time_Hours','Satisfaction_Score','Ticket_Channel_Email','Ticket_Channel_Web Form','Issue_Category_Billing','Issue_Category_Fraud','Issue_Category_General Inquiry','Issue_Category_Technical']))
meta_prob = meta_model.predict_proba(X_test[['Resolution_Time_Hours','Satisfaction_Score','Ticket_Channel_Email','Ticket_Channel_Web Form','Issue_Category_Billing','Issue_Category_Fraud','Issue_Category_General Inquiry','Issue_Category_Technical']])

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.033553 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 97920
[LightGBM] [Info] Number of data points in the train set: 16000, number of used features: 384
[LightGBM] [Info] Start training from score -0.943052
[LightGBM] [Info] Start training from score -1.663696
[LightGBM] [Info] Start training from score -1.058430
[LightGBM] [Info] Start training from score -2.602002
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000189 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 139
[LightGBM] [Info] Number of data points in the train set: 16000, number of used features: 8
[LightGBM] [Info] Start training from score -0.943052
[LightGBM] [Info] Start training from score -1.663696
[LightGBM] [Info] Start training from score -1.058430
[LightGBM] [Info] Start training from score -2.602002

In [198]:
final_prob = 0.6*emb_prob + 0.4*meta_prob
y_pred = []
for prob in final_prob:
    y_pred.append(np.argmax(prob))

report = classification_report(y_test,y_pred)
print("Classfication report\n")
print(report)
print("Mismatch Report\n")
yp_mismatch = (priority_test != y_pred).astype(int)
report = classification_report(mismatch_test,yp_mismatch)
print(report)

Classfication report

              precision    recall  f1-score   support

           0       0.95      0.93      0.94      1558
           1       0.93      0.97      0.95       757
           2       0.92      0.92      0.92      1388
           3       0.90      0.90      0.90       297

    accuracy                           0.93      4000
   macro avg       0.92      0.93      0.93      4000
weighted avg       0.93      0.93      0.93      4000

Mismatch Report

              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1394
           1       0.97      0.97      0.97      2606

    accuracy                           0.96      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.96      0.96      0.96      4000